-- AUTO-GENERATED by scripts/generate_tracker_logic.py -- do not edit by hand.
-- Source of truth: SMBW Archipelago apworld data/{regions,locations,items}.json
-- Implements AP reachability: full(R) = R.requires AND OR(full(parents)).

local GEN = 0
local RCACHE = {}
ScriptHost:AddWatchForCode("smbw_logic_invalidate", "*", function() GEN = GEN + 1 end)

-- Open-world mode: SLOT_DATA (set by autotracking/archipelago.lua) carries
-- open_world (0/1), open_world_active (list of active world numbers) and
-- palaces_required.  When off / unset, the standard linear-spine logic runs.
local function SMBW_OPEN()
    return SLOT_DATA ~= nil and (SLOT_DATA.open_world == 1 or SLOT_DATA.open_world == true)
end
local function smbw_world_active(n)
    if not (SLOT_DATA and SLOT_DATA.open_world_active) then return false end
    for _, w in ipairs(SLOT_DATA.open_world_active) do
        if w == n then return true end
    end
    return false
end
-- Bowser gate in open-world: enough active-world Royal Seeds (palaces) cleared.
function smbw_open_palaces()
    local active = (SLOT_DATA and SLOT_DATA.open_world_active) or {}
    local need = (SLOT_DATA and SLOT_DATA.palaces_required) or #active
    local have = 0
    for _, n in ipairs(active) do
        if Tracker:ProviderCountForCode("w" .. n .. "royalseed") > 0 then have = have + 1 end
    end
    if have >= tonumber(need) then return ACCESS_NORMAL end
    return ACCESS_NONE
end

-- |@Royal Seed:n| category gate -- sum of the six world Royal Seeds.
function smbw_royal(n)
    local c = Tracker:ProviderCountForCode("w1royalseed")
        + Tracker:ProviderCountForCode("w2royalseed")
        + Tracker:ProviderCountForCode("w3royalseed")
        + Tracker:ProviderCountForCode("w4royalseed")
        + Tracker:ProviderCountForCode("w5royalseed")
        + Tracker:ProviderCountForCode("w6royalseed")
    if c >= tonumber(n) then return ACCESS_NORMAL end
    return ACCESS_NONE
end

-- Region reachability (topologically ordered: parents before children).
local function R_W1_Start()
    local hit = RCACHE["R_W1_Start"]
    if hit and hit.gen == GEN then return hit.v end
    local v
    if SMBW_OPEN() then v = ALL(smbw_world_active(1)) else v = ACCESS_NORMAL end
    RCACHE["R_W1_Start"] = {gen = GEN, v = v}
    return v
end
local function R_W1_3_Seeds()
    local hit = RCACHE["R_W1_3_Seeds"]
    if hit and hit.gen == GEN then return hit.v end
    local v = ALL(ALL(HAS("w1wonderseed", 3, 3), HAS("parachutecapbadge")), R_W1_Start())
    RCACHE["R_W1_3_Seeds"] = {gen = GEN, v = v}
    return v
end
local function R_W1_10_Seeds()
    local hit = RCACHE["R_W1_10_Seeds"]
    if hit and hit.gen == GEN then return hit.v end
    local v = ALL(ALL(HAS("w1wonderseed", 10, 10), HAS("autosupermushroombadge")), R_W1_3_Seeds())
    RCACHE["R_W1_10_Seeds"] = {gen = GEN, v = v}
    return v
end
local function R_W1_Post_Bulrush_Express()
    local hit = RCACHE["R_W1_Post_Bulrush_Express"]
    if hit and hit.gen == GEN then return hit.v end
    local v = ALL(ANY(HAS("elephantfruit"), HAS("drillmushroom")), R_W1_10_Seeds())
    RCACHE["R_W1_Post_Bulrush_Express"] = {gen = GEN, v = v}
    return v
end
local function R_W1_Post_Jet_Run()
    local hit = RCACHE["R_W1_Post_Jet_Run"]
    if hit and hit.gen == GEN then return hit.v end
    local v = R_W1_Post_Bulrush_Express()
    RCACHE["R_W1_Post_Jet_Run"] = {gen = GEN, v = v}
    return v
end
local function R_W1_14_Seeds()
    local hit = RCACHE["R_W1_14_Seeds"]
    if hit and hit.gen == GEN then return hit.v end
    local v = ALL(HAS("w1wonderseed", 14, 14), R_W1_10_Seeds())
    RCACHE["R_W1_14_Seeds"] = {gen = GEN, v = v}
    return v
end
local function R_PI_Pre_W2()
    local hit = RCACHE["R_PI_Pre_W2"]
    if hit and hit.gen == GEN then return hit.v end
    local v
    if SMBW_OPEN() then v = ACCESS_NONE else v = R_W1_14_Seeds() end
    RCACHE["R_PI_Pre_W2"] = {gen = GEN, v = v}
    return v
end
local function R_PI_Pre_W2_2_Seeds()
    local hit = RCACHE["R_PI_Pre_W2_2_Seeds"]
    if hit and hit.gen == GEN then return hit.v end
    local v
    if SMBW_OPEN() then v = ACCESS_NONE else v = ALL(HAS("petalisleswonderseed", 2, 2), R_PI_Pre_W2()) end
    RCACHE["R_PI_Pre_W2_2_Seeds"] = {gen = GEN, v = v}
    return v
end
local function R_PI_5_Seeds()
    local hit = RCACHE["R_PI_5_Seeds"]
    if hit and hit.gen == GEN then return hit.v end
    local v
    if SMBW_OPEN() then v = ACCESS_NONE else v = ALL(HAS("petalisleswonderseed", 5, 5), R_PI_Pre_W2_2_Seeds()) end
    RCACHE["R_PI_5_Seeds"] = {gen = GEN, v = v}
    return v
end
local function R_PI_8_Seeds()
    local hit = RCACHE["R_PI_8_Seeds"]
    if hit and hit.gen == GEN then return hit.v end
    local v
    if SMBW_OPEN() then v = ACCESS_NONE else v = ALL(HAS("petalisleswonderseed", 8, 8), R_PI_5_Seeds()) end
    RCACHE["R_PI_8_Seeds"] = {gen = GEN, v = v}
    return v
end
local function R_W2_Start()
    local hit = RCACHE["R_W2_Start"]
    if hit and hit.gen == GEN then return hit.v end
    local v
    if SMBW_OPEN() then v = ALL(smbw_world_active(2)) else v = ALL(HAS("petalisleswonderseed", 5, 5), R_PI_Pre_W2_2_Seeds()) end
    RCACHE["R_W2_Start"] = {gen = GEN, v = v}
    return v
end
local function R_W2_4_Seeds()
    local hit = RCACHE["R_W2_4_Seeds"]
    if hit and hit.gen == GEN then return hit.v end
    local v = ALL(HAS("w2wonderseed", 4, 4), R_W2_Start())
    RCACHE["R_W2_4_Seeds"] = {gen = GEN, v = v}
    return v
end
local function R_W2_Post_Jump()
    local hit = RCACHE["R_W2_Post_Jump"]
    if hit and hit.gen == GEN then return hit.v end
    local v = R_W2_4_Seeds()
    RCACHE["R_W2_Post_Jump"] = {gen = GEN, v = v}
    return v
end
local function R_W2_9_Seeds()
    local hit = RCACHE["R_W2_9_Seeds"]
    if hit and hit.gen == GEN then return hit.v end
    local v = ALL(HAS("w2wonderseed", 9, 9), R_W2_4_Seeds())
    RCACHE["R_W2_9_Seeds"] = {gen = GEN, v = v}
    return v
end
local function R_W2_14_Seeds()
    local hit = RCACHE["R_W2_14_Seeds"]
    if hit and hit.gen == GEN then return hit.v end
    local v = ALL(HAS("w2wonderseed", 14, 14), R_W2_9_Seeds())
    RCACHE["R_W2_14_Seeds"] = {gen = GEN, v = v}
    return v
end
local function R_PI_Pre_W3()
    local hit = RCACHE["R_PI_Pre_W3"]
    if hit and hit.gen == GEN then return hit.v end
    local v
    if SMBW_OPEN() then v = ACCESS_NONE else v = R_W2_14_Seeds() end
    RCACHE["R_PI_Pre_W3"] = {gen = GEN, v = v}
    return v
end
local function R_W3_Start()
    local hit = RCACHE["R_W3_Start"]
    if hit and hit.gen == GEN then return hit.v end
    local v
    if SMBW_OPEN() then v = ALL(smbw_world_active(3)) else v = ALL(HAS("petalisleswonderseed", 8, 8), R_PI_Pre_W3()) end
    RCACHE["R_W3_Start"] = {gen = GEN, v = v}
    return v
end
local function R_W3_4_Seeds()
    local hit = RCACHE["R_W3_4_Seeds"]
    if hit and hit.gen == GEN then return hit.v end
    local v = ALL(ALL(HAS("w3wonderseed", 4, 4), HAS("crouchinghighjumpbadge")), R_W3_Start())
    RCACHE["R_W3_4_Seeds"] = {gen = GEN, v = v}
    return v
end
local function R_W3_10_Seeds()
    local hit = RCACHE["R_W3_10_Seeds"]
    if hit and hit.gen == GEN then return hit.v end
    local v = ALL(HAS("w3wonderseed", 10, 10), R_W3_4_Seeds())
    RCACHE["R_W3_10_Seeds"] = {gen = GEN, v = v}
    return v
end
local function R_PI_Pre_W4()
    local hit = RCACHE["R_PI_Pre_W4"]
    if hit and hit.gen == GEN then return hit.v end
    local v
    if SMBW_OPEN() then v = ACCESS_NONE else v = R_W3_10_Seeds() end
    RCACHE["R_PI_Pre_W4"] = {gen = GEN, v = v}
    return v
end
local function R_W4_Start()
    local hit = RCACHE["R_W4_Start"]
    if hit and hit.gen == GEN then return hit.v end
    local v
    if SMBW_OPEN() then v = ALL(smbw_world_active(4)) else v = ALL(HAS("petalisleswonderseed", 10, 10), R_PI_Pre_W4()) end
    RCACHE["R_W4_Start"] = {gen = GEN, v = v}
    return v
end
local function R_W4_Post_Invis()
    local hit = RCACHE["R_W4_Post_Invis"]
    if hit and hit.gen == GEN then return hit.v end
    local v = R_W4_Start()
    RCACHE["R_W4_Post_Invis"] = {gen = GEN, v = v}
    return v
end
local function R_W4_15_Seeds()
    local hit = RCACHE["R_W4_15_Seeds"]
    if hit and hit.gen == GEN then return hit.v end
    local v = ALL(HAS("w4wonderseed", 15, 15), R_W4_Start())
    RCACHE["R_W4_15_Seeds"] = {gen = GEN, v = v}
    return v
end
local function R_PI_Post_Airship()
    local hit = RCACHE["R_PI_Post_Airship"]
    if hit and hit.gen == GEN then return hit.v end
    local v
    if SMBW_OPEN() then v = ACCESS_NONE else v = R_PI_Pre_W4() end
    RCACHE["R_PI_Post_Airship"] = {gen = GEN, v = v}
    return v
end
local function R_W5_Start()
    local hit = RCACHE["R_W5_Start"]
    if hit and hit.gen == GEN then return hit.v end
    local v
    if SMBW_OPEN() then v = ALL(smbw_world_active(5)) else v = ALL(HAS("petalisleswonderseed", 12, 12), R_PI_Post_Airship()) end
    RCACHE["R_W5_Start"] = {gen = GEN, v = v}
    return v
end
local function R_W5_6_Seeds()
    local hit = RCACHE["R_W5_6_Seeds"]
    if hit and hit.gen == GEN then return hit.v end
    local v = ALL(HAS("w5wonderseed", 6, 6), R_W5_Start())
    RCACHE["R_W5_6_Seeds"] = {gen = GEN, v = v}
    return v
end
local function R_W5_Post_Wubba()
    local hit = RCACHE["R_W5_Post_Wubba"]
    if hit and hit.gen == GEN then return hit.v end
    local v = R_W5_6_Seeds()
    RCACHE["R_W5_Post_Wubba"] = {gen = GEN, v = v}
    return v
end
local function R_W5_Post_Swaying()
    local hit = RCACHE["R_W5_Post_Swaying"]
    if hit and hit.gen == GEN then return hit.v end
    local v = R_W5_Post_Wubba()
    RCACHE["R_W5_Post_Swaying"] = {gen = GEN, v = v}
    return v
end
local function R_W5_11_Seeds()
    local hit = RCACHE["R_W5_11_Seeds"]
    if hit and hit.gen == GEN then return hit.v end
    local v = ALL(HAS("w5wonderseed", 11, 11), R_W5_Post_Swaying())
    RCACHE["R_W5_11_Seeds"] = {gen = GEN, v = v}
    return v
end
local function R_W6_Start()
    local hit = RCACHE["R_W6_Start"]
    if hit and hit.gen == GEN then return hit.v end
    local v
    if SMBW_OPEN() then v = ALL(smbw_world_active(6)) else v = ALL(HAS("petalisleswonderseed", 15, 15), R_PI_Post_Airship()) end
    RCACHE["R_W6_Start"] = {gen = GEN, v = v}
    return v
end
local function R_W6_25_Seeds()
    local hit = RCACHE["R_W6_25_Seeds"]
    if hit and hit.gen == GEN then return hit.v end
    local v = ALL(HAS("w6wonderseed", 25, 25), R_W6_Start())
    RCACHE["R_W6_25_Seeds"] = {gen = GEN, v = v}
    return v
end
local function R_W6_Post_Spring()
    local hit = RCACHE["R_W6_Post_Spring"]
    if hit and hit.gen == GEN then return hit.v end
    local v = R_W6_25_Seeds()
    RCACHE["R_W6_Post_Spring"] = {gen = GEN, v = v}
    return v
end
local function R_World_Bowser()
    local hit = RCACHE["R_World_Bowser"]
    if hit and hit.gen == GEN then return hit.v end
    local v
    if SMBW_OPEN() then v = smbw_open_palaces() else v = ALL(smbw_royal(6), R_W6_Start()) end
    RCACHE["R_World_Bowser"] = {gen = GEN, v = v}
    return v
end
local function R_Pre_W4_Special()
    local hit = RCACHE["R_Pre_W4_Special"]
    if hit and hit.gen == GEN then return hit.v end
    local v
    if SMBW_OPEN() then v = ACCESS_NONE else v = ALL(ALL(HAS("specialworldwonderseed", 6, 6), ANY(HAS("elephantfruit"), HAS("petalisleswonderseed", 10, 10), ALL(HAS("w5wonderseed", 11, 11), HAS("petalisleswonderseed", 12, 12)))), R_PI_Pre_W4()) end
    RCACHE["R_Pre_W4_Special"] = {gen = GEN, v = v}
    return v
end
local function R_Special_End()
    local hit = RCACHE["R_Special_End"]
    if hit and hit.gen == GEN then return hit.v end
    local v
    if SMBW_OPEN() then v = ACCESS_NONE else v = ALL(ALL(HAS("elephantfruit"), HAS("w5wonderseed", 11, 11), HAS("specialworldwonderseed", 16, 16)), R_W6_Post_Spring()) end
    RCACHE["R_Special_End"] = {gen = GEN, v = v}
    return v
end
local function R_Post_Badge()
    local hit = RCACHE["R_Post_Badge"]
    if hit and hit.gen == GEN then return hit.v end
    local v
    if SMBW_OPEN() then v = ACCESS_NONE else v = ALL(ALL(HAS("w1wonderseed", 14, 14), HAS("w2wonderseed", 14, 14), HAS("w3wonderseed", 10, 10), HAS("w4wonderseed", 15, 15), HAS("w5wonderseed", 11, 11), HAS("w6wonderseed", 25, 25), HAS("petalisleswonderseed", 15, 15), HAS("specialworldwonderseed", 16, 16), smbw_royal(6)), R_Special_End()) end
    RCACHE["R_Post_Badge"] = {gen = GEN, v = v}
    return v
end

-- Per-AP-location access rules.
local LOC = {}
LOC["14887804500"] = function() return R_W1_Start() end
LOC["14887804501"] = function() return R_W1_Start() end
LOC["14887804502"] = function() return R_W1_Start() end
LOC["14887804503"] = function() return R_W1_Start() end
LOC["14887804504"] = function() return R_W1_Start() end
LOC["14887804505"] = function() return R_W1_Start() end
LOC["14887804506"] = function() return R_W1_Start() end
LOC["14887804507"] = function() return R_W1_Start() end
LOC["14887804508"] = function() return R_W1_Start() end
LOC["14887804509"] = function() return R_W1_Start() end
LOC["14887804510"] = function() return R_W1_Start() end
LOC["14887804511"] = function() return R_W1_Start() end
LOC["14887804512"] = function() return R_W1_Start() end
LOC["14887804513"] = function() return R_W1_Start() end
LOC["14887804514"] = function() return R_W1_Start() end
LOC["14887804515"] = function() return R_W1_Start() end
LOC["14887804516"] = function() return R_W1_Start() end
LOC["14887804517"] = function() return R_W1_Start() end
LOC["14887804518"] = function() return R_W1_Start() end
LOC["14887804519"] = function() return ALL(R_W1_3_Seeds(), HAS("parachutecapbadge")) end
LOC["14887804520"] = function() return R_W1_3_Seeds() end
LOC["14887804521"] = function() return R_W1_3_Seeds() end
LOC["14887804522"] = function() return R_W1_3_Seeds() end
LOC["14887804523"] = function() return R_W1_3_Seeds() end
LOC["14887804524"] = function() return R_W1_3_Seeds() end
LOC["14887804525"] = function() return R_W1_3_Seeds() end
LOC["14887804526"] = function() return R_W1_3_Seeds() end
LOC["14887804527"] = function() return R_W1_3_Seeds() end
LOC["14887804528"] = function() return R_W1_3_Seeds() end
LOC["14887804529"] = function() return R_W1_3_Seeds() end
LOC["14887804530"] = function() return R_W1_3_Seeds() end
LOC["14887804531"] = function() return R_W1_3_Seeds() end
LOC["14887804532"] = function() return R_W1_3_Seeds() end
LOC["14887804533"] = function() return R_W1_3_Seeds() end
LOC["14887804534"] = function() return R_W1_3_Seeds() end
LOC["14887804535"] = function() return R_W1_3_Seeds() end
LOC["14887804536"] = function() return R_W1_3_Seeds() end
LOC["14887804537"] = function() return R_W1_3_Seeds() end
LOC["14887804538"] = function() return R_W1_3_Seeds() end
LOC["14887804539"] = function() return R_W1_3_Seeds() end
LOC["14887804540"] = function() return R_W1_3_Seeds() end
LOC["14887804541"] = function() return R_W1_3_Seeds() end
LOC["14887804542"] = function() return R_W1_3_Seeds() end
LOC["14887804543"] = function() return R_W1_3_Seeds() end
LOC["14887804544"] = function() return R_W1_3_Seeds() end
LOC["14887804545"] = function() return R_W1_3_Seeds() end
LOC["14887804546"] = function() return R_W1_3_Seeds() end
LOC["14887804547"] = function() return R_W1_3_Seeds() end
LOC["14887804548"] = function() return ALL(R_W1_10_Seeds(), HAS("autosupermushroombadge")) end
LOC["14887804549"] = function() return R_W1_10_Seeds() end
LOC["14887804550"] = function() return R_W1_10_Seeds() end
LOC["14887804551"] = function() return R_W1_10_Seeds() end
LOC["14887804552"] = function() return R_W1_10_Seeds() end
LOC["14887804553"] = function() return R_W1_10_Seeds() end
LOC["14887804554"] = function() return R_W1_10_Seeds() end
LOC["14887804555"] = function() return R_W1_10_Seeds() end
LOC["14887804556"] = function() return R_W1_10_Seeds() end
LOC["14887804557"] = function() return R_W1_10_Seeds() end
LOC["14887804558"] = function() return R_W1_10_Seeds() end
LOC["14887804559"] = function() return R_W1_10_Seeds() end
LOC["14887804560"] = function() return R_W1_10_Seeds() end
LOC["14887804561"] = function() return R_W1_10_Seeds() end
LOC["14887804562"] = function() return ALL(R_W1_10_Seeds(), HAS("elephantfruit")) end
LOC["14887804563"] = function() return R_W1_10_Seeds() end
LOC["14887804564"] = function() return R_W1_10_Seeds() end
LOC["14887804565"] = function() return R_W1_10_Seeds() end
LOC["14887804566"] = function() return R_W1_10_Seeds() end
LOC["14887804567"] = function() return R_W1_10_Seeds() end
LOC["14887804568"] = function() return ALL(R_W1_10_Seeds(), HAS("wall-climbjumpbadge")) end
LOC["14887804569"] = function() return ALL(R_W1_10_Seeds(), HAS("wall-climbjumpbadge")) end
LOC["14887804570"] = function() return ALL(R_W1_10_Seeds(), HAS("wall-climbjumpbadge")) end
LOC["14887804571"] = function() return ALL(R_W1_10_Seeds(), HAS("wall-climbjumpbadge")) end
LOC["14887804572"] = function() return ALL(R_W1_10_Seeds(), HAS("wall-climbjumpbadge")) end
LOC["14887804573"] = function() return R_W1_10_Seeds() end
LOC["14887804574"] = function() return R_W1_10_Seeds() end
LOC["14887804575"] = function() return R_W1_10_Seeds() end
LOC["14887804576"] = function() return R_W1_10_Seeds() end
LOC["14887804577"] = function() return R_W1_Post_Bulrush_Express() end
LOC["14887804578"] = function() return R_W1_Post_Bulrush_Express() end
LOC["14887804579"] = function() return R_W1_Post_Bulrush_Express() end
LOC["14887804580"] = function() return R_W1_Post_Bulrush_Express() end
LOC["14887804581"] = function() return R_W1_Post_Bulrush_Express() end
LOC["14887804582"] = function() return R_W1_Post_Bulrush_Express() end
LOC["14887804583"] = function() return R_W1_Post_Bulrush_Express() end
LOC["14887804584"] = function() return R_W1_Post_Bulrush_Express() end
LOC["14887804585"] = function() return R_W1_Post_Bulrush_Express() end
LOC["14887804586"] = function() return R_W1_Post_Bulrush_Express() end
LOC["14887804587"] = function() return R_W1_Post_Bulrush_Express() end
LOC["14887804588"] = function() return R_W1_Post_Bulrush_Express() end
LOC["14887804589"] = function() return ALL(R_W1_Post_Jet_Run(), HAS("jetrunbadge")) end
LOC["14887804590"] = function() return ALL(R_W1_Post_Jet_Run(), HAS("jetrunbadge")) end
LOC["14887804591"] = function() return ALL(R_W1_Post_Jet_Run(), HAS("jetrunbadge")) end
LOC["14887804592"] = function() return ALL(R_W1_Post_Jet_Run(), HAS("jetrunbadge")) end
LOC["14887804593"] = function() return ALL(R_W1_Post_Jet_Run(), HAS("jetrunbadge")) end
LOC["14887804594"] = function() return R_W1_Post_Jet_Run() end
LOC["14887804595"] = function() return R_W1_Post_Jet_Run() end
LOC["14887804596"] = function() return R_W1_Post_Jet_Run() end
LOC["14887804597"] = function() return R_W1_Post_Jet_Run() end
LOC["14887804598"] = function() return R_W1_Post_Jet_Run() end
LOC["14887804599"] = function() return R_W1_Post_Jet_Run() end
LOC["14887804600"] = function() return R_W1_14_Seeds() end
LOC["14887804601"] = function() return R_W1_14_Seeds() end
LOC["14887804602"] = function() return R_W1_14_Seeds() end
LOC["14887804603"] = function() return ALL(R_W1_14_Seeds(), HAS("elephantfruit")) end
LOC["14887804604"] = function() return R_W1_14_Seeds() end
LOC["14887804605"] = function() return ALL(R_W1_3_Seeds(), HAS("parachutecapbadge")) end
LOC["14887804606"] = function() return ALL(R_W1_10_Seeds(), HAS("wall-climbjumpbadge")) end
LOC["14887804607"] = function() return R_W1_3_Seeds() end
LOC["14887804608"] = function() return ALL(R_W1_10_Seeds(), HAS("autosupermushroombadge")) end
LOC["14887804609"] = function() return ALL(R_W1_Post_Jet_Run(), HAS("jetrunbadge")) end
LOC["14887804610"] = function() return R_PI_Pre_W2() end
LOC["14887804611"] = function() return R_PI_Pre_W2() end
LOC["14887804612"] = function() return R_PI_Pre_W2() end
LOC["14887804613"] = function() return R_PI_Pre_W2() end
LOC["14887804614"] = function() return R_PI_Pre_W2() end
LOC["14887804615"] = function() return R_PI_Pre_W2() end
LOC["14887804616"] = function() return R_PI_Pre_W2() end
LOC["14887804617"] = function() return ALL(R_PI_Pre_W2(), HAS("dolphinkickbadge")) end
LOC["14887804618"] = function() return ALL(R_PI_Pre_W2(), HAS("dolphinkickbadge")) end
LOC["14887804619"] = function() return ALL(R_PI_Pre_W2(), HAS("dolphinkickbadge")) end
LOC["14887804620"] = function() return ALL(R_PI_Pre_W2(), HAS("dolphinkickbadge")) end
LOC["14887804621"] = function() return ALL(R_PI_Pre_W2(), HAS("dolphinkickbadge")) end
LOC["14887804622"] = function() return R_PI_Pre_W2_2_Seeds() end
LOC["14887804623"] = function() return R_PI_Pre_W2_2_Seeds() end
LOC["14887804624"] = function() return R_PI_Pre_W2_2_Seeds() end
LOC["14887804625"] = function() return R_PI_Pre_W2_2_Seeds() end
LOC["14887804626"] = function() return R_PI_Pre_W2_2_Seeds() end
LOC["14887804627"] = function() return R_PI_Pre_W2_2_Seeds() end
LOC["14887804628"] = function() return R_PI_Pre_W2_2_Seeds() end
LOC["14887804629"] = function() return R_PI_Pre_W2_2_Seeds() end
LOC["14887804630"] = function() return R_PI_Pre_W2_2_Seeds() end
LOC["14887804631"] = function() return R_PI_Pre_W2_2_Seeds() end
LOC["14887804632"] = function() return R_PI_Pre_W2_2_Seeds() end
LOC["14887804633"] = function() return ALL(R_PI_Pre_W2_2_Seeds(), HAS("bubbleflower")) end
LOC["14887804634"] = function() return R_W2_Start() end
LOC["14887804635"] = function() return R_W2_Start() end
LOC["14887804636"] = function() return R_W2_Start() end
LOC["14887804637"] = function() return R_W2_Start() end
LOC["14887804638"] = function() return R_W2_Start() end
LOC["14887804639"] = function() return R_W2_Start() end
LOC["14887804640"] = function() return R_W2_Start() end
LOC["14887804641"] = function() return R_W2_Start() end
LOC["14887804642"] = function() return R_W2_Start() end
LOC["14887804643"] = function() return R_W2_Start() end
LOC["14887804644"] = function() return R_W2_Start() end
LOC["14887804645"] = function() return R_W2_Start() end
LOC["14887804646"] = function() return R_W2_Start() end
LOC["14887804647"] = function() return ALL(R_W2_Start(), HAS("wall-climbjumpbadge")) end
LOC["14887804648"] = function() return ALL(R_W2_Start(), HAS("wall-climbjumpbadge")) end
LOC["14887804649"] = function() return ALL(R_W2_Start(), HAS("wall-climbjumpbadge")) end
LOC["14887804650"] = function() return ALL(R_W2_Start(), HAS("wall-climbjumpbadge")) end
LOC["14887804651"] = function() return ALL(R_W2_Start(), HAS("wall-climbjumpbadge")) end
LOC["14887804652"] = function() return R_W2_Start() end
LOC["14887804653"] = function() return R_W2_Start() end
LOC["14887804654"] = function() return R_W2_4_Seeds() end
LOC["14887804655"] = function() return R_W2_4_Seeds() end
LOC["14887804656"] = function() return R_W2_4_Seeds() end
LOC["14887804657"] = function() return R_W2_4_Seeds() end
LOC["14887804658"] = function() return R_W2_4_Seeds() end
LOC["14887804659"] = function() return R_W2_4_Seeds() end
LOC["14887804660"] = function() return R_W2_4_Seeds() end
LOC["14887804661"] = function() return R_W2_4_Seeds() end
LOC["14887804662"] = function() return R_W2_4_Seeds() end
LOC["14887804663"] = function() return R_W2_4_Seeds() end
LOC["14887804664"] = function() return R_W2_4_Seeds() end
LOC["14887804665"] = function() return R_W2_4_Seeds() end
LOC["14887804666"] = function() return R_W2_4_Seeds() end
LOC["14887804667"] = function() return R_W2_4_Seeds() end
LOC["14887804668"] = function() return R_W2_4_Seeds() end
LOC["14887804669"] = function() return R_W2_4_Seeds() end
LOC["14887804670"] = function() return R_W2_4_Seeds() end
LOC["14887804671"] = function() return R_W2_4_Seeds() end
LOC["14887804672"] = function() return R_W2_4_Seeds() end
LOC["14887804673"] = function() return ALL(R_W2_4_Seeds(), HAS("floatinghighjumpbadge")) end
LOC["14887804674"] = function() return ALL(R_W2_4_Seeds(), HAS("floatinghighjumpbadge")) end
LOC["14887804675"] = function() return ALL(R_W2_4_Seeds(), HAS("floatinghighjumpbadge")) end
LOC["14887804676"] = function() return ALL(R_W2_4_Seeds(), HAS("floatinghighjumpbadge")) end
LOC["14887804677"] = function() return ALL(R_W2_4_Seeds(), HAS("floatinghighjumpbadge")) end
LOC["14887804678"] = function() return R_W2_4_Seeds() end
LOC["14887804679"] = function() return R_W2_4_Seeds() end
LOC["14887804680"] = function() return R_W2_4_Seeds() end
LOC["14887804681"] = function() return R_W2_4_Seeds() end
LOC["14887804682"] = function() return R_W2_4_Seeds() end
LOC["14887804683"] = function() return ALL(R_W2_Post_Jump(), HAS("springfeetbadge")) end
LOC["14887804684"] = function() return ALL(R_W2_Post_Jump(), HAS("springfeetbadge")) end
LOC["14887804685"] = function() return ALL(R_W2_Post_Jump(), HAS("springfeetbadge")) end
LOC["14887804686"] = function() return ALL(R_W2_Post_Jump(), HAS("springfeetbadge")) end
LOC["14887804687"] = function() return ALL(R_W2_Post_Jump(), HAS("springfeetbadge")) end
LOC["14887804688"] = function() return R_W2_Post_Jump() end
LOC["14887804689"] = function() return R_W2_Post_Jump() end
LOC["14887804690"] = function() return R_W2_Post_Jump() end
LOC["14887804691"] = function() return R_W2_Post_Jump() end
LOC["14887804692"] = function() return R_W2_Post_Jump() end
LOC["14887804693"] = function() return R_W2_Post_Jump() end
LOC["14887804694"] = function() return R_W2_9_Seeds() end
LOC["14887804695"] = function() return R_W2_9_Seeds() end
LOC["14887804696"] = function() return R_W2_9_Seeds() end
LOC["14887804697"] = function() return R_W2_9_Seeds() end
LOC["14887804698"] = function() return R_W2_9_Seeds() end
LOC["14887804699"] = function() return R_W2_9_Seeds() end
LOC["14887804700"] = function() return R_W2_9_Seeds() end
LOC["14887804701"] = function() return R_W2_9_Seeds() end
LOC["14887804702"] = function() return R_W2_9_Seeds() end
LOC["14887804703"] = function() return R_W2_9_Seeds() end
LOC["14887804704"] = function() return R_W2_9_Seeds() end
LOC["14887804705"] = function() return R_W2_9_Seeds() end
LOC["14887804706"] = function() return R_W2_9_Seeds() end
LOC["14887804707"] = function() return R_W2_9_Seeds() end
LOC["14887804708"] = function() return R_W2_9_Seeds() end
LOC["14887804709"] = function() return R_W2_9_Seeds() end
LOC["14887804710"] = function() return R_W2_9_Seeds() end
LOC["14887804711"] = function() return R_W2_9_Seeds() end
LOC["14887804712"] = function() return R_W2_9_Seeds() end
LOC["14887804713"] = function() return R_W2_9_Seeds() end
LOC["14887804714"] = function() return ALL(R_W2_9_Seeds(), ANY(HAS("elephantfruit"), HAS("bubbleflower"))) end
LOC["14887804715"] = function() return R_W2_9_Seeds() end
LOC["14887804716"] = function() return R_W2_9_Seeds() end
LOC["14887804717"] = function() return R_W2_9_Seeds() end
LOC["14887804718"] = function() return R_W2_4_Seeds() end
LOC["14887804719"] = function() return R_W2_9_Seeds() end
LOC["14887804720"] = function() return R_W2_14_Seeds() end
LOC["14887804721"] = function() return R_W2_14_Seeds() end
LOC["14887804722"] = function() return R_W2_14_Seeds() end
LOC["14887804723"] = function() return R_W2_14_Seeds() end
LOC["14887804724"] = function() return R_W2_14_Seeds() end
LOC["14887804725"] = function() return ALL(R_PI_Pre_W2(), HAS("dolphinkickbadge")) end
LOC["14887804726"] = function() return ALL(R_W2_4_Seeds(), HAS("floatinghighjumpbadge")) end
LOC["14887804727"] = function() return R_PI_Pre_W2_2_Seeds() end
LOC["14887804728"] = function() return R_W2_9_Seeds() end
LOC["14887804729"] = function() return ALL(R_W2_Post_Jump(), HAS("springfeetbadge")) end
LOC["14887804730"] = function() return R_W2_Start() end
LOC["14887804731"] = function() return R_PI_Pre_W2_2_Seeds() end
LOC["14887804732"] = function() return ALL(R_PI_5_Seeds(), HAS("dolphinkickbadge")) end
LOC["14887804733"] = function() return ALL(R_PI_5_Seeds(), HAS("dolphinkickbadge")) end
LOC["14887804734"] = function() return ALL(R_PI_5_Seeds(), HAS("dolphinkickbadge")) end
LOC["14887804735"] = function() return ALL(R_PI_5_Seeds(), HAS("dolphinkickbadge")) end
LOC["14887804736"] = function() return ALL(R_PI_5_Seeds(), HAS("dolphinkickbadge")) end
LOC["14887804737"] = function() return R_PI_5_Seeds() end
LOC["14887804738"] = function() return R_PI_5_Seeds() end
LOC["14887804739"] = function() return R_PI_5_Seeds() end
LOC["14887804740"] = function() return R_PI_5_Seeds() end
LOC["14887804741"] = function() return R_PI_5_Seeds() end
LOC["14887804742"] = function() return R_PI_5_Seeds() end
LOC["14887804743"] = function() return R_PI_5_Seeds() end
LOC["14887804744"] = function() return R_W3_Start() end
LOC["14887804745"] = function() return R_W3_Start() end
LOC["14887804746"] = function() return R_W3_Start() end
LOC["14887804747"] = function() return R_W3_Start() end
LOC["14887804748"] = function() return R_W3_Start() end
LOC["14887804749"] = function() return R_W3_Start() end
LOC["14887804750"] = function() return R_W3_Start() end
LOC["14887804751"] = function() return R_W3_Start() end
LOC["14887804752"] = function() return R_W3_Start() end
LOC["14887804753"] = function() return R_W3_Start() end
LOC["14887804754"] = function() return R_W3_Start() end
LOC["14887804755"] = function() return R_W3_Start() end
LOC["14887804756"] = function() return ALL(R_W3_Start(), HAS("elephantfruit")) end
LOC["14887804757"] = function() return R_W3_Start() end
LOC["14887804758"] = function() return R_W3_Start() end
LOC["14887804759"] = function() return R_W3_Start() end
LOC["14887804760"] = function() return R_W3_Start() end
LOC["14887804761"] = function() return ALL(R_W3_4_Seeds(), HAS("crouchinghighjumpbadge")) end
LOC["14887804762"] = function() return ALL(R_W3_4_Seeds(), HAS("crouchinghighjumpbadge")) end
LOC["14887804763"] = function() return ALL(R_W3_4_Seeds(), HAS("crouchinghighjumpbadge")) end
LOC["14887804764"] = function() return ALL(R_W3_4_Seeds(), HAS("crouchinghighjumpbadge")) end
LOC["14887804765"] = function() return ALL(R_W3_4_Seeds(), HAS("crouchinghighjumpbadge")) end
LOC["14887804766"] = function() return R_W3_4_Seeds() end
LOC["14887804767"] = function() return R_W3_4_Seeds() end
LOC["14887804768"] = function() return R_W3_4_Seeds() end
LOC["14887804769"] = function() return R_W3_4_Seeds() end
LOC["14887804770"] = function() return R_W3_4_Seeds() end
LOC["14887804771"] = function() return R_W3_4_Seeds() end
LOC["14887804772"] = function() return R_W3_4_Seeds() end
LOC["14887804773"] = function() return R_W3_4_Seeds() end
LOC["14887804774"] = function() return R_W3_4_Seeds() end
LOC["14887804775"] = function() return R_W3_4_Seeds() end
LOC["14887804776"] = function() return R_W3_4_Seeds() end
LOC["14887804777"] = function() return R_W3_4_Seeds() end
LOC["14887804778"] = function() return R_W3_4_Seeds() end
LOC["14887804779"] = function() return R_W3_4_Seeds() end
LOC["14887804780"] = function() return R_W3_4_Seeds() end
LOC["14887804781"] = function() return R_W3_4_Seeds() end
LOC["14887804782"] = function() return R_W3_4_Seeds() end
LOC["14887804783"] = function() return R_W3_4_Seeds() end
LOC["14887804784"] = function() return R_W3_4_Seeds() end
LOC["14887804785"] = function() return R_W3_4_Seeds() end
LOC["14887804786"] = function() return R_W3_10_Seeds() end
LOC["14887804787"] = function() return R_W3_10_Seeds() end
LOC["14887804788"] = function() return R_W3_10_Seeds() end
LOC["14887804789"] = function() return R_W3_10_Seeds() end
LOC["14887804790"] = function() return R_W3_10_Seeds() end
LOC["14887804791"] = function() return R_W3_10_Seeds() end
LOC["14887804792"] = function() return R_W3_10_Seeds() end
LOC["14887804793"] = function() return R_W3_10_Seeds() end
LOC["14887804794"] = function() return R_W3_10_Seeds() end
LOC["14887804795"] = function() return R_W3_10_Seeds() end
LOC["14887804796"] = function() return R_W3_10_Seeds() end
LOC["14887804797"] = function() return R_W3_10_Seeds() end
LOC["14887804798"] = function() return R_W3_10_Seeds() end
LOC["14887804799"] = function() return R_W3_10_Seeds() end
LOC["14887804800"] = function() return R_W3_10_Seeds() end
LOC["14887804801"] = function() return ALL(R_W3_4_Seeds(), HAS("crouchinghighjumpbadge")) end
LOC["14887804802"] = function() return R_PI_8_Seeds() end
LOC["14887804803"] = function() return R_PI_8_Seeds() end
LOC["14887804804"] = function() return R_PI_8_Seeds() end
LOC["14887804805"] = function() return R_PI_8_Seeds() end
LOC["14887804806"] = function() return R_PI_8_Seeds() end
LOC["14887804807"] = function() return R_PI_8_Seeds() end
LOC["14887804808"] = function() return R_PI_8_Seeds() end
LOC["14887804809"] = function() return R_W4_Start() end
LOC["14887804810"] = function() return R_W4_Start() end
LOC["14887804811"] = function() return R_W4_Start() end
LOC["14887804812"] = function() return R_W4_Start() end
LOC["14887804813"] = function() return R_W4_Start() end
LOC["14887804814"] = function() return R_W4_Start() end
LOC["14887804815"] = function() return R_W4_Start() end
LOC["14887804816"] = function() return R_W4_Start() end
LOC["14887804817"] = function() return R_W4_Start() end
LOC["14887804818"] = function() return R_W4_Start() end
LOC["14887804819"] = function() return R_W4_Start() end
LOC["14887804820"] = function() return R_W4_Start() end
LOC["14887804821"] = function() return R_W4_Start() end
LOC["14887804822"] = function() return R_W4_Start() end
LOC["14887804823"] = function() return R_W4_Start() end
LOC["14887804824"] = function() return R_W4_Start() end
LOC["14887804825"] = function() return R_W4_Start() end
LOC["14887804826"] = function() return R_W4_Start() end
LOC["14887804827"] = function() return R_W4_Start() end
LOC["14887804828"] = function() return ALL(R_W4_Start(), HAS("rhythmjumpbadge")) end
LOC["14887804829"] = function() return ALL(R_W4_Start(), HAS("rhythmjumpbadge")) end
LOC["14887804830"] = function() return ALL(R_W4_Start(), HAS("rhythmjumpbadge")) end
LOC["14887804831"] = function() return ALL(R_W4_Start(), HAS("rhythmjumpbadge")) end
LOC["14887804832"] = function() return ALL(R_W4_Start(), HAS("rhythmjumpbadge")) end
LOC["14887804833"] = function() return ALL(R_W4_Start(), HAS("rhythmjumpbadge")) end
LOC["14887804834"] = function() return R_W4_Start() end
LOC["14887804835"] = function() return R_W4_Start() end
LOC["14887804836"] = function() return R_W4_Start() end
LOC["14887804837"] = function() return R_W4_Start() end
LOC["14887804838"] = function() return R_W4_Start() end
LOC["14887804839"] = function() return R_W4_Start() end
LOC["14887804840"] = function() return R_W4_Start() end
LOC["14887804841"] = function() return R_W4_Start() end
LOC["14887804842"] = function() return R_W4_Start() end
LOC["14887804843"] = function() return R_W4_Start() end
LOC["14887804844"] = function() return R_W4_Start() end
LOC["14887804845"] = function() return R_W4_Start() end
LOC["14887804846"] = function() return R_W4_Start() end
LOC["14887804847"] = function() return R_W4_Start() end
LOC["14887804848"] = function() return R_W4_Start() end
LOC["14887804849"] = function() return R_W4_Start() end
LOC["14887804850"] = function() return R_W4_Start() end
LOC["14887804851"] = function() return R_W4_Start() end
LOC["14887804852"] = function() return R_W4_Start() end
LOC["14887804853"] = function() return R_W4_Start() end
LOC["14887804854"] = function() return R_W4_Start() end
LOC["14887804855"] = function() return R_W4_Start() end
LOC["14887804856"] = function() return R_W4_Start() end
LOC["14887804857"] = function() return R_W4_Start() end
LOC["14887804858"] = function() return R_W4_Start() end
LOC["14887804859"] = function() return R_W4_Start() end
LOC["14887804860"] = function() return R_W4_Start() end
LOC["14887804861"] = function() return R_W4_Start() end
LOC["14887804862"] = function() return R_W4_Start() end
LOC["14887804863"] = function() return R_W4_Start() end
LOC["14887804864"] = function() return R_W4_Start() end
LOC["14887804865"] = function() return R_W4_Start() end
LOC["14887804866"] = function() return R_W4_Start() end
LOC["14887804867"] = function() return R_W4_Start() end
LOC["14887804868"] = function() return R_W4_Start() end
LOC["14887804869"] = function() return R_W4_Start() end
LOC["14887804870"] = function() return ALL(R_W4_Start(), HAS("crouchinghighjumpbadge")) end
LOC["14887804871"] = function() return ALL(R_W4_Start(), HAS("crouchinghighjumpbadge")) end
LOC["14887804872"] = function() return ALL(R_W4_Start(), HAS("crouchinghighjumpbadge")) end
LOC["14887804873"] = function() return ALL(R_W4_Start(), HAS("crouchinghighjumpbadge")) end
LOC["14887804874"] = function() return ALL(R_W4_Start(), HAS("crouchinghighjumpbadge")) end
LOC["14887804875"] = function() return ALL(R_W4_Start(), HAS("invisibilitybadge")) end
LOC["14887804876"] = function() return ALL(R_W4_Start(), HAS("invisibilitybadge")) end
LOC["14887804877"] = function() return ALL(R_W4_Start(), HAS("invisibilitybadge")) end
LOC["14887804878"] = function() return ALL(R_W4_Start(), HAS("invisibilitybadge")) end
LOC["14887804879"] = function() return ALL(R_W4_Start(), HAS("invisibilitybadge")) end
LOC["14887804880"] = function() return R_W4_Start() end
LOC["14887804881"] = function() return R_W4_Start() end
LOC["14887804882"] = function() return R_W4_Start() end
LOC["14887804883"] = function() return R_W4_Start() end
LOC["14887804884"] = function() return R_W4_Start() end
LOC["14887804885"] = function() return ALL(R_W4_Start(), HAS("drillmushroom")) end
LOC["14887804886"] = function() return R_W4_Start() end
LOC["14887804887"] = function() return R_W4_Start() end
LOC["14887804888"] = function() return R_W4_Start() end
LOC["14887804889"] = function() return R_W4_Start() end
LOC["14887804890"] = function() return R_W4_Start() end
LOC["14887804891"] = function() return R_W4_Start() end
LOC["14887804892"] = function() return R_W4_Start() end
LOC["14887804893"] = function() return R_W4_Start() end
LOC["14887804894"] = function() return R_W4_Start() end
LOC["14887804895"] = function() return R_W4_Post_Invis() end
LOC["14887804896"] = function() return R_W4_Post_Invis() end
LOC["14887804897"] = function() return R_W4_Post_Invis() end
LOC["14887804898"] = function() return R_W4_Post_Invis() end
LOC["14887804899"] = function() return R_W4_Post_Invis() end
LOC["14887804900"] = function() return R_W4_Post_Invis() end
LOC["14887804901"] = function() return R_W4_15_Seeds() end
LOC["14887804902"] = function() return R_W4_15_Seeds() end
LOC["14887804903"] = function() return R_W4_15_Seeds() end
LOC["14887804904"] = function() return R_W4_15_Seeds() end
LOC["14887804905"] = function() return R_W4_15_Seeds() end
LOC["14887804906"] = function() return R_W4_Start() end
LOC["14887804907"] = function() return R_W4_Start() end
LOC["14887804908"] = function() return ALL(R_W4_Start(), HAS("rhythmjumpbadge")) end
LOC["14887804909"] = function() return ALL(R_W4_Post_Invis(), HAS("invisibilitybadge")) end
LOC["14887804910"] = function() return R_PI_8_Seeds() end
LOC["14887804911"] = function() return R_PI_8_Seeds() end
LOC["14887804912"] = function() return R_PI_8_Seeds() end
LOC["14887804913"] = function() return R_PI_8_Seeds() end
LOC["14887804914"] = function() return R_PI_8_Seeds() end
LOC["14887804915"] = function() return R_PI_8_Seeds() end
LOC["14887804916"] = function() return R_PI_8_Seeds() end
LOC["14887804917"] = function() return R_PI_8_Seeds() end
LOC["14887804918"] = function() return R_PI_8_Seeds() end
LOC["14887804919"] = function() return R_PI_8_Seeds() end
LOC["14887804920"] = function() return R_PI_8_Seeds() end
LOC["14887804921"] = function() return R_PI_8_Seeds() end
LOC["14887804922"] = function() return R_PI_8_Seeds() end
LOC["14887804923"] = function() return R_PI_8_Seeds() end
LOC["14887804924"] = function() return R_PI_8_Seeds() end
LOC["14887804925"] = function() return R_PI_8_Seeds() end
LOC["14887804926"] = function() return R_PI_8_Seeds() end
LOC["14887804927"] = function() return ALL(R_PI_8_Seeds(), HAS("boostingspinjumpbadge")) end
LOC["14887804928"] = function() return ALL(R_PI_8_Seeds(), HAS("boostingspinjumpbadge")) end
LOC["14887804929"] = function() return ALL(R_PI_8_Seeds(), HAS("boostingspinjumpbadge")) end
LOC["14887804930"] = function() return ALL(R_PI_8_Seeds(), HAS("boostingspinjumpbadge")) end
LOC["14887804931"] = function() return ALL(R_PI_8_Seeds(), HAS("boostingspinjumpbadge")) end
LOC["14887804932"] = function() return R_PI_8_Seeds() end
LOC["14887804933"] = function() return R_PI_8_Seeds() end
LOC["14887804934"] = function() return R_PI_8_Seeds() end
LOC["14887804935"] = function() return R_PI_8_Seeds() end
LOC["14887804936"] = function() return R_PI_8_Seeds() end
LOC["14887804937"] = function() return ALL(R_PI_8_Seeds(), HAS("boostingspinjumpbadge")) end
LOC["14887804938"] = function() return R_PI_8_Seeds() end
LOC["14887804939"] = function() return R_PI_8_Seeds() end
LOC["14887804940"] = function() return R_PI_8_Seeds() end
LOC["14887804941"] = function() return R_PI_8_Seeds() end
LOC["14887804942"] = function() return R_PI_8_Seeds() end
LOC["14887804943"] = function() return R_PI_8_Seeds() end
LOC["14887804944"] = function() return R_W5_Start() end
LOC["14887804945"] = function() return R_W5_Start() end
LOC["14887804946"] = function() return R_W5_Start() end
LOC["14887804947"] = function() return R_W5_Start() end
LOC["14887804948"] = function() return R_W5_Start() end
LOC["14887804949"] = function() return R_W5_Start() end
LOC["14887804950"] = function() return R_W5_Start() end
LOC["14887804951"] = function() return R_W5_Start() end
LOC["14887804952"] = function() return R_W5_Start() end
LOC["14887804953"] = function() return R_W5_Start() end
LOC["14887804954"] = function() return R_W5_Start() end
LOC["14887804955"] = function() return R_W5_Start() end
LOC["14887804956"] = function() return R_W5_Start() end
LOC["14887804957"] = function() return R_W5_Start() end
LOC["14887804958"] = function() return R_W5_Start() end
LOC["14887804959"] = function() return R_W5_Start() end
LOC["14887804960"] = function() return R_W5_Start() end
LOC["14887804961"] = function() return R_W5_Start() end
LOC["14887804962"] = function() return R_W5_Start() end
LOC["14887804963"] = function() return R_W5_Start() end
LOC["14887804964"] = function() return R_W5_Start() end
LOC["14887804965"] = function() return R_W5_Start() end
LOC["14887804966"] = function() return R_W5_Start() end
LOC["14887804967"] = function() return R_W5_Start() end
LOC["14887804968"] = function() return R_W5_Start() end
LOC["14887804969"] = function() return R_W5_Start() end
LOC["14887804970"] = function() return R_W5_Start() end
LOC["14887804971"] = function() return R_W5_Start() end
LOC["14887804972"] = function() return R_W5_6_Seeds() end
LOC["14887804973"] = function() return R_W5_6_Seeds() end
LOC["14887804974"] = function() return R_W5_6_Seeds() end
LOC["14887804975"] = function() return R_W5_6_Seeds() end
LOC["14887804976"] = function() return R_W5_6_Seeds() end
LOC["14887804977"] = function() return R_W5_6_Seeds() end
LOC["14887804978"] = function() return R_W5_6_Seeds() end
LOC["14887804979"] = function() return R_W5_Post_Wubba() end
LOC["14887804980"] = function() return R_W5_Post_Wubba() end
LOC["14887804981"] = function() return R_W5_Post_Wubba() end
LOC["14887804982"] = function() return R_W5_Post_Wubba() end
LOC["14887804983"] = function() return R_W5_Post_Wubba() end
LOC["14887804984"] = function() return R_W5_Post_Wubba() end
LOC["14887804985"] = function() return R_W5_Post_Wubba() end
LOC["14887804986"] = function() return ALL(R_W5_Post_Wubba(), HAS("grapplingvinebadge")) end
LOC["14887804987"] = function() return ALL(R_W5_Post_Wubba(), HAS("grapplingvinebadge")) end
LOC["14887804988"] = function() return ALL(R_W5_Post_Wubba(), HAS("grapplingvinebadge")) end
LOC["14887804989"] = function() return ALL(R_W5_Post_Wubba(), HAS("grapplingvinebadge")) end
LOC["14887804990"] = function() return ALL(R_W5_Post_Wubba(), HAS("grapplingvinebadge")) end
LOC["14887804991"] = function() return R_W5_Post_Swaying() end
LOC["14887804992"] = function() return R_W5_Post_Swaying() end
LOC["14887804993"] = function() return R_W5_Post_Swaying() end
LOC["14887804994"] = function() return R_W5_Post_Swaying() end
LOC["14887804995"] = function() return R_W5_11_Seeds() end
LOC["14887804996"] = function() return R_W5_11_Seeds() end
LOC["14887804997"] = function() return R_W5_11_Seeds() end
LOC["14887804998"] = function() return R_W5_11_Seeds() end
LOC["14887804999"] = function() return R_W5_11_Seeds() end
LOC["14887805000"] = function() return R_W5_11_Seeds() end
LOC["14887805001"] = function() return R_W5_11_Seeds() end
LOC["14887805002"] = function() return R_W5_11_Seeds() end
LOC["14887805003"] = function() return R_W5_11_Seeds() end
LOC["14887805004"] = function() return R_W5_11_Seeds() end
LOC["14887805005"] = function() return R_W5_11_Seeds() end
LOC["14887805006"] = function() return R_W5_11_Seeds() end
LOC["14887805007"] = function() return R_W5_11_Seeds() end
LOC["14887805008"] = function() return R_W5_11_Seeds() end
LOC["14887805009"] = function() return R_W5_11_Seeds() end
LOC["14887805010"] = function() return ALL(R_W5_6_Seeds(), HAS("grapplingvinebadge")) end
LOC["14887805011"] = function() return ALL(R_W5_Start(), HAS("sensorbadge")) end
LOC["14887805012"] = function() return R_W5_Start() end
LOC["14887805013"] = function() return R_W6_Start() end
LOC["14887805014"] = function() return R_W6_Start() end
LOC["14887805015"] = function() return ALL(R_W6_Start(), HAS("drillmushroom")) end
LOC["14887805016"] = function() return R_W6_Start() end
LOC["14887805017"] = function() return R_W6_Start() end
LOC["14887805018"] = function() return R_W6_Start() end
LOC["14887805019"] = function() return ALL(R_W6_Start(), HAS("drillmushroom")) end
LOC["14887805020"] = function() return R_W6_Start() end
LOC["14887805021"] = function() return R_W6_Start() end
LOC["14887805022"] = function() return R_W6_Start() end
LOC["14887805023"] = function() return R_W6_Start() end
LOC["14887805024"] = function() return R_W6_Start() end
LOC["14887805025"] = function() return R_W6_Start() end
LOC["14887805026"] = function() return ALL(R_W6_Start(), HAS("drillmushroom")) end
LOC["14887805027"] = function() return R_W6_Start() end
LOC["14887805028"] = function() return R_W6_Start() end
LOC["14887805029"] = function() return R_W6_Start() end
LOC["14887805030"] = function() return R_W6_Start() end
LOC["14887805031"] = function() return R_W6_Start() end
LOC["14887805032"] = function() return R_W6_Start() end
LOC["14887805033"] = function() return R_W6_Start() end
LOC["14887805034"] = function() return R_W6_Start() end
LOC["14887805035"] = function() return R_W6_Start() end
LOC["14887805036"] = function() return R_W6_Start() end
LOC["14887805037"] = function() return R_W6_Start() end
LOC["14887805038"] = function() return R_W6_Start() end
LOC["14887805039"] = function() return R_W6_Start() end
LOC["14887805040"] = function() return R_W6_Start() end
LOC["14887805041"] = function() return R_W6_Start() end
LOC["14887805042"] = function() return R_W6_Start() end
LOC["14887805043"] = function() return ALL(R_W6_Start(), HAS("elephantfruit")) end
LOC["14887805044"] = function() return R_W6_Start() end
LOC["14887805045"] = function() return R_W6_Start() end
LOC["14887805046"] = function() return R_W6_Start() end
LOC["14887805047"] = function() return R_W6_Start() end
LOC["14887805048"] = function() return R_W6_Start() end
LOC["14887805049"] = function() return R_W6_Start() end
LOC["14887805050"] = function() return R_W6_Start() end
LOC["14887805051"] = function() return R_W6_Start() end
LOC["14887805052"] = function() return R_W6_Start() end
LOC["14887805053"] = function() return R_W6_Start() end
LOC["14887805054"] = function() return R_W6_Start() end
LOC["14887805055"] = function() return R_W6_Start() end
LOC["14887805056"] = function() return R_W6_Start() end
LOC["14887805057"] = function() return ALL(R_W6_Start(), HAS("floatinghighjumpbadge")) end
LOC["14887805058"] = function() return ALL(R_W6_Start(), HAS("floatinghighjumpbadge")) end
LOC["14887805059"] = function() return ALL(R_W6_Start(), HAS("floatinghighjumpbadge")) end
LOC["14887805060"] = function() return ALL(R_W6_Start(), HAS("floatinghighjumpbadge")) end
LOC["14887805061"] = function() return ALL(R_W6_Start(), HAS("floatinghighjumpbadge")) end
LOC["14887805062"] = function() return ALL(R_W6_Start(), ALL(HAS("boostingspinjumpbadge"), HAS("drillmushroom"))) end
LOC["14887805063"] = function() return ALL(R_W6_Start(), ALL(HAS("boostingspinjumpbadge"), HAS("drillmushroom"))) end
LOC["14887805064"] = function() return ALL(R_W6_Start(), ALL(HAS("boostingspinjumpbadge"), HAS("drillmushroom"))) end
LOC["14887805065"] = function() return ALL(R_W6_Start(), ALL(HAS("boostingspinjumpbadge"), HAS("drillmushroom"))) end
LOC["14887805066"] = function() return ALL(R_W6_Start(), ALL(HAS("boostingspinjumpbadge"), HAS("drillmushroom"))) end
LOC["14887805067"] = function() return ALL(R_W6_Start(), HAS("grapplingvinebadge")) end
LOC["14887805068"] = function() return ALL(R_W6_Start(), HAS("grapplingvinebadge")) end
LOC["14887805069"] = function() return ALL(R_W6_Start(), HAS("grapplingvinebadge")) end
LOC["14887805070"] = function() return ALL(R_W6_Start(), HAS("grapplingvinebadge")) end
LOC["14887805071"] = function() return ALL(R_W6_Start(), HAS("grapplingvinebadge")) end
LOC["14887805072"] = function() return R_W6_Start() end
LOC["14887805073"] = function() return R_W6_Start() end
LOC["14887805074"] = function() return R_W6_Start() end
LOC["14887805075"] = function() return R_W6_Start() end
LOC["14887805076"] = function() return ALL(R_W6_Start(), ALL(HAS("elephantfruit"), HAS("bubbleflower"), HAS("drillmushroom"))) end
LOC["14887805077"] = function() return ALL(R_W6_Start(), HAS("elephantfruit")) end
LOC["14887805078"] = function() return R_W6_Start() end
LOC["14887805079"] = function() return R_W6_Start() end
LOC["14887805080"] = function() return R_W6_Start() end
LOC["14887805081"] = function() return R_W6_Start() end
LOC["14887805082"] = function() return R_W6_25_Seeds() end
LOC["14887805083"] = function() return R_W6_25_Seeds() end
LOC["14887805084"] = function() return R_W6_25_Seeds() end
LOC["14887805085"] = function() return R_W6_25_Seeds() end
LOC["14887805086"] = function() return R_W6_25_Seeds() end
LOC["14887805087"] = function() return ALL(R_W6_25_Seeds(), HAS("jetrunbadge")) end
LOC["14887805088"] = function() return ALL(R_W6_25_Seeds(), HAS("jetrunbadge")) end
LOC["14887805089"] = function() return ALL(R_W6_25_Seeds(), HAS("jetrunbadge")) end
LOC["14887805090"] = function() return ALL(R_W6_25_Seeds(), HAS("jetrunbadge")) end
LOC["14887805091"] = function() return ALL(R_W6_25_Seeds(), HAS("jetrunbadge")) end
LOC["14887805092"] = function() return ALL(R_W6_25_Seeds(), HAS("invisibilitybadge")) end
LOC["14887805093"] = function() return ALL(R_W6_25_Seeds(), HAS("invisibilitybadge")) end
LOC["14887805094"] = function() return ALL(R_W6_25_Seeds(), HAS("invisibilitybadge")) end
LOC["14887805095"] = function() return ALL(R_W6_25_Seeds(), HAS("invisibilitybadge")) end
LOC["14887805096"] = function() return ALL(R_W6_25_Seeds(), HAS("invisibilitybadge")) end
LOC["14887805097"] = function() return ALL(R_W6_25_Seeds(), HAS("springfeetbadge")) end
LOC["14887805098"] = function() return ALL(R_W6_25_Seeds(), HAS("springfeetbadge")) end
LOC["14887805099"] = function() return ALL(R_W6_25_Seeds(), HAS("springfeetbadge")) end
LOC["14887805100"] = function() return ALL(R_W6_25_Seeds(), HAS("springfeetbadge")) end
LOC["14887805101"] = function() return ALL(R_W6_25_Seeds(), HAS("springfeetbadge")) end
LOC["14887805102"] = function() return R_W6_Post_Spring() end
LOC["14887805103"] = function() return R_W6_Post_Spring() end
LOC["14887805104"] = function() return R_W6_Post_Spring() end
LOC["14887805105"] = function() return R_W6_Post_Spring() end
LOC["14887805106"] = function() return R_W6_Post_Spring() end
LOC["14887805107"] = function() return R_W6_Post_Spring() end
LOC["14887805108"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805109"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805110"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805111"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805112"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805113"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805114"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805115"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805116"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805117"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805118"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805119"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805120"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805121"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805122"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805123"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805124"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805125"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805126"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805127"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805128"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805129"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805130"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805131"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805132"] = function() return R_World_Bowser() end
LOC["14887805133"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805134"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805135"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805136"] = function() if SMBW_OPEN() then return ACCESS_NONE end return R_World_Bowser() end
LOC["14887805137"] = function() return R_Pre_W4_Special() end
LOC["14887805138"] = function() return R_Pre_W4_Special() end
LOC["14887805139"] = function() return R_Pre_W4_Special() end
LOC["14887805140"] = function() return R_Pre_W4_Special() end
LOC["14887805141"] = function() return R_Pre_W4_Special() end
LOC["14887805142"] = function() return R_Pre_W4_Special() end
LOC["14887805143"] = function() return R_Special_End() end
LOC["14887805144"] = function() return R_Special_End() end
LOC["14887805145"] = function() return R_Special_End() end
LOC["14887805146"] = function() return R_Special_End() end
LOC["14887805147"] = function() return R_Special_End() end
LOC["14887805148"] = function() return R_Special_End() end
LOC["14887805149"] = function() return R_Post_Badge() end
LOC["14887805150"] = function() return R_Post_Badge() end
LOC["14887805151"] = function() return R_Post_Badge() end
LOC["14887805152"] = function() return R_Post_Badge() end
LOC["14887805153"] = function() return R_Post_Badge() end
LOC["14887805154"] = function() return ALL(R_Post_Badge(), HAS("soundoff?badge")) end
LOC["14887805155"] = function() return ALL(R_Post_Badge(), HAS("soundoff?badge")) end
LOC["14887805156"] = function() return R_W5_11_Seeds() end
LOC["14887805157"] = function() return R_PI_8_Seeds() end
LOC["14887805158"] = function() return R_PI_8_Seeds() end
LOC["14887805159"] = function() return R_PI_8_Seeds() end
LOC["14887805160"] = function() return R_PI_8_Seeds() end
LOC["14887805161"] = function() return R_PI_8_Seeds() end
LOC["14887805162"] = function() return R_PI_8_Seeds() end

function smbw_loc(id)
    local f = LOC[id]
    if f then return f() end
    return ACCESS_NORMAL
end

